### ISSUE TITLE
Javascript in Pattern Library

### ISSUE THREAD

**Issue by arobillard** [the-spice-mice/web-app#29]
Hi @thomasjbradley

Is there a way to have the javascript I have written work in my patterns inside of the pattern library? It currently works as expected on the `index.html`, but when looking at specific patterns it isn't brought in. I can add script tags into the actual pattern's html file to make it work. But by doing so it'll bring in it into final `index.html` page multiple times.

It isn't a huge issue as I still have multiple ways to test it for now, just curious if there is a way to do it.

Thanks!

**Comment by thomasjbradley** [comment]
It works the same way as the CSS does.

Make a `main.js` file inside your `js` folder, do any `{% include_relative %}`s that you want from within the `js` folder for global/common JS files. Then add the tag `{% pattern_js %}` at the bottom of `main.js`. Patternbot will find all the JS files from within each pattern and include them into the `main.js`. That `main.js` is then added into each pattern too, just like the `main.css` for testing within Patternbot.
