### ISSUE TITLE
Pulling in data error in Patternbot vs on index page

### ISSUE THREAD

**Issue by arobillard** [the-spice-mice/web-app#72]
Hi @thomasjbradley

I was working more on using data loops on our app and am having another issue. On Monday we were able to get the data to work properly in the `index.html`, however now it is not working properly in the pattern library.

I think the problem is that in the Patternbot default example the rating data is being written as a string with quotations so it isn't reading it correctly. However, I am not sure how to set up the defaults to not include the quotations.

Any help is appreciated! Thanks!

![screen shot 2019-02-08 at 10 04 27 am](https://user-images.githubusercontent.com/22084666/52486534-649c7580-2b89-11e9-98d5-c180e075f23e.png)
![screen shot 2019-02-08 at 10 03 35 am](https://user-images.githubusercontent.com/22084666/52486532-649c7580-2b89-11e9-9e64-0ab6e07c7aad.png)
![screen shot 2019-02-08 at 10 05 17 am](https://user-images.githubusercontent.com/22084666/52486535-649c7580-2b89-11e9-8501-e6ccc7d14128.png)

**Comment by thomasjbradley** [comment]
Yep—that’s exactly the problem. It’s a bug in Patternbot.
Patternbot needs to detect whether quotes are needed or not an create it’s example appropriately.

I’ll get back to you when I fix the problem.

**Comment by arobillard** [comment]
Ok thanks! It isn't hindering me from being able to wok so there is no major rush.

**Comment by thomasjbradley** [comment]
This should be fixed now!

```
gem install jekyll_patternbot
bundle update
```

I’ve also added categories to the CSS `@utility` & `@var` comments: use `+` then some word (or words separated by `-`). Some examples:

```css
:root {
  /* @var +border The default border radius */
  --border-radius: 8px;
}

/* @utility +font-related Set the text to the primary typeface */
.font-primary {}
```
