### ISSUE TITLE
Logo Sketches

### ISSUE THREAD

**Issue by hollixholton** [the-spice-mice/web-app#8]
Each team member is to create a minimum of 10 logo sketches each.

**Comment by hollixholton** [comment]
![photo 2019-01-21 12 22 02 pm](https://user-images.githubusercontent.com/22149848/51489784-4d7f1a80-1d77-11e9-88e3-040212863e43.jpg)

Holli's Logo Sketches

**Comment by ksheedy** [comment]
![katie-logo-sketches](https://user-images.githubusercontent.com/22224979/51490507-7dc7b880-1d79-11e9-8010-1cd0ee04f012.jpg)

**Comment by ksheedy** [comment]
![50255275_627639377694784_7933039874020474880_n](https://user-images.githubusercontent.com/22224979/51491249-b9fc1880-1d7b-11e9-8d7f-4825bbaccc42.jpg)
